### PR TITLE
 Move NUsight modules that are used by both client and server into `src/shared`

### PR DESCRIPTION
**Pull request by JosephusPaye**
The modules `base/compose` and `fourcc` are both used in the server as well, so this moves them from `src/client` into `src/shared`.

### CODE REVIEW

**Comment by tayloryoung6396** [comment]
4Tel enforcing their conventions on us again 🤦

**Review by TrentHouliston — APPROVED** [review]
Looks good to me!

**Comment by WongAaronSW** [comment]
> 4Tel enforcing their conventions on us again 🤦

Trents Convention.

**Comment by tayloryoung6396** [comment]
> Looks good to me!

Not sure I trust Trents review

**Comment by TrentHouliston** [comment]
> > 4Tel enforcing their conventions on us again 🤦
> 
> Trents Convention.

Hey this was @JosephusPaye's convention not mine

**Comment by JosephusPaye** [comment]
> > > 4Tel enforcing their conventions on us again facepalm
> > 
> > 
> > Trents Convention.
> 
> Hey this was @JosephusPaye's convention not mine

Hey I'm just enforcing the convention we already have :P

**Pull request merged**
