### PR TITLE
Rename master->main

### PR DESCRIPTION
**Pull request by Y0sh1dk**
Update references to main due to renaming of master branch.

`./b target` was telling me my docker build context had changed but I hadn't touched it!, then noticed it was `diff`ing with master and not main :thinking:

### CODE REVIEW

**Comment by KipHamiltons** [comment]
Almost :stuck_out_tongue: You missed the build badges on the README. They'll need to be updated after GHA is approved, but we haven't done that yet :sweat_smile:

**Comment by Y0sh1dk** [comment]
I decided to leave them because github actions should be in soon (hopfully :sweat_smile: ), But there you go, updated the references in there too.

**Review by KipHamiltons — APPROVED** [review]
Thank you sir

**Comment by JosephusPaye** [comment]
The badge URLs might need editing beyond just `master` -> `main` (e.g. the numeric identifier might be different for the different branch).

Also, Buildkite was still building `master` as your main branch, but I've updated that.

**Comment by Y0sh1dk** [comment]
>The badge URLs might need editing beyond just master -> main (e.g. the numeric identifier might be different for the different branch).

Just noticed this, I dont have access to the pipeline settings in buildkite where you grab the url from, are you able to update it @JosephusPaye or @KipHamiltons ?

**Pull request merged**
