### PR TITLE
Moved iterable type trait

### PR DESCRIPTION
**Pull request by CMurtagh-LGTM**

### CODE REVIEW

**Comment by KipHamiltons** [comment]
If this is fully replaced by range concepts in c++20, why don't we add C++20 for that module that uses this type trait?

**Review by Bidski — COMMENTED** [review]
Is this needed for something?

**Comment by KipHamiltons** [comment]
@Bidski see [these comments](https://github.com/NUbots/NUbots/pull/467#discussion_r653194435)
Just a quick thing Cameron noted while reviewing #467

**Comment by CMurtagh-LGTM** [comment]
> Is this needed for something?

#467 removes the anon namespace, and I don't like that this type trait just sitting in the header file.

**Review by Bidski — APPROVED** [review]
Sure, I guess

**Pull request merged**
