### PR TITLE
Fix the mutex inside FileWatcher to make it reentrant + Fix unit test.

### PR DESCRIPTION
**Pull request by CMurtagh-LGTM**
Made FileWatcher mutex less restrictive, so you can now have a FileWatch inside a FileWatch without the internal mutex waiting for itself to unlock.

### CODE REVIEW

**Comment by ElderNoSpace** [comment]
Need the modern cmake.

**Comment by KipHamiltons** [comment]
Modern CMake has arrived ;)

**Comment by KipHamiltons** [comment]
This is [wip] - what needs to be done to finish it?

**Comment by CMurtagh-LGTM** [comment]
> This is [wip] - what needs to be done to finish it?

Can't remember, I've reread it and it looks fine. Maybe check that the test passes on your computer.

**Comment by KipHamiltons** [comment]
The tests pass on my arch desktop. I don't feel like I'm in a position to review this though

**Review by TrentHouliston — CHANGES_REQUESTED** [review]

**Review by TrentHouliston — APPROVED** [review]

**Pull request merged**
