### PR TITLE
Removes WalkPathFollower

### PR DESCRIPTION
**Pull request by KipHamiltons**
This module is unused and I don't think we have plans to use it (see discussion on #398). This PR removes it.

### CODE REVIEW

**Review by TrentHouliston — COMMENTED** [review]
I mean, this was the code that let us follow a walk path plan, do we no longer need to do that?

**Comment by ysims** [comment]
> I mean, this was the code that let us follow a walk path plan, do we no longer need to do that?

The walk path planner emits a walk command which is used by the walk engine - we don't use this follower module.

**Comment by KipHamiltons** [comment]
> > I mean, this was the code that let us follow a walk path plan, do we no longer need to do that?
> 
> The walk path planner emits a walk command which is used by the walk engine - we don't use this follower module.

Would the static walk use it?

**Comment by ysims** [comment]
> > > I mean, this was the code that let us follow a walk path plan, do we no longer need to do that?
> > 
> > 
> > The walk path planner emits a walk command which is used by the walk engine - we don't use this follower module.
> 
> Would the static walk use it?

Any walk engine, including the static walk, will use a walk command. 
What Trent is saying sounds more like
walk path planner --(on some message)--> walk follower --(on walk command)--> walk engine
The walk engine doesn't care if the planner or the follower gives it the walk command. It's more about what the planner emits. 

This follower module sounds like something @TheCoolKidsTable was after for his planner idea.

**Comment by TrentHouliston** [comment]
Yeah, this takes a list of waypoints and walks to them in sequence.
You can just make your walk path planner skip this module

**Comment by KipHamiltons** [comment]
What's the consensus then? are we keen to keep this one?

**Review by ysims — APPROVED** [review]
Delete 🤖 
It's not used and we plan to rewrite the walk path planner anyway.

**Pull request merged**
