### PR TITLE
Adds new HardwareIO for nugus2

### PR DESCRIPTION
**Pull request by Crafty15**
- Adjusted for metal legs
- Adjusts shoulder pitch so horn zero (Zombie) position is straight up (Same as n1 and n3)

### CODE REVIEW

**Review by ysims — COMMENTED** [review]
If it's the same as n3, then we should probably just make this the default and only have a specific one for n1

**Comment by Crafty15** [comment]
> If it's the same as n3, then we should probably just make this the default and only have a specific one for n1

Gonna have to double check what i've done here. Looks like i have the same IO for n1 and n2, with the minor differences in hip and knee values.

**Comment by Crafty15** [comment]
> > If it's the same as n3, then we should probably just make this the default and only have a specific one for n1
> 
> Gonna have to double check what i've done here. Looks like i have the same IO for n1 and n2, with the minor differences in hip and knee values.

I checked them side by side and they are slightly different

**Review by ysims — APPROVED** [review]
lgtm

**Pull request merged**
