### PR TITLE
Tune walk

### PR DESCRIPTION
**Pull request by Tom0Brien**
This PR adds a tune for the walk on real robot.

Update - L.Craft
- Both robots seem to be reacting well to speed changes. So be aware that when using keyboard walk, a setting of 0.100 will barely move, and a setting of 2,000-ish will take off like a flash.
- Might not play to well if the start speed is too high when walking autonomously. 
- Works fine with both types of hips.

### CODE REVIEW

**Review by LachlanCourt — DISMISSED** [review]

**Review by ysims — CHANGES_REQUESTED** [review]
Can we double check these particularly on n3 since it seemed to not work the other day

**Comment by Tom0Brien** [comment]
Yeah will need do.

**Review by Crafty15 — DISMISSED** [review]
LGTM

**Comment by ysims** [comment]
I am curious about the walk command - the walk engine does have an upper bound (walk command changes step length) so at some point making it higher will do nothing new and you'll get a warning from the walk engine saying something about xy being too big and it's truncating to the maximum step length. At what point does this happen?

**Review by ysims — APPROVED** [review]
lgtm

**Pull request merged**
