### PR TITLE
Fixes left kick

### PR DESCRIPTION
**Pull request by weepeefa**

### CODE REVIEW

**Comment by wongjoel** [comment]
I just tested this in `kid.wbt`: for me, the robot kicks the ground with its left foot, then falls over due to kicking the ground. Because the robot kicks the ground where the foot was, it doesn't end up moving a ball placed right in front of the foot. I assume it was different when you were tuning it?

**Review by Bidski — DISMISSED** [review]
I assume this actually works?

**Comment by KipHamiltons** [comment]
Worked on my machine. Definite improvement

**Review by KipHamiltons — APPROVED** [review]
LGTM. Tested on another computer. Very stable, decent power. Excellent work

**Pull request merged**
