### PR TITLE
Update yarn tool import

### PR DESCRIPTION
**Pull request by Y0sh1dk**
- Fix `WrapPty` import to relfect changes in #376 
- Pass nusight2 pre-push checks by running `yarn eslint:fix` in `/NUbots/nusight2`. `./b format` didn't seem to format these, should be investigated.

### CODE REVIEW

**Comment by TrentHouliston** [comment]
Lots of unrelated changes in this PR

**Comment by Y0sh1dk** [comment]
> Lots of unrelated changes in this PR

The changes to the nusight files were the only way I could push or publish my branch.
All I did was:

 - Branch off latest master
 - Fix import
 - Went to publish branch but could not due to husky pre-push errors
 - Ran `yarn eslint:fix` in `/NUbots/nusight2` to fix formatting errors which allowed to push.

**Comment by KipHamiltons** [comment]
Did you want this broken up into a 4 line formatting PR and a fix import PR instead @TrentHouliston?

**Comment by TrentHouliston** [comment]
I'm just concerned as to how those changes could have gotten in in the first place, whatever PR they came from shouldn't have been able to merge

**Review by TrentHouliston — APPROVED** [review]

**Pull request merged**
