### PR TITLE
Add tools for working with nbs files in c++

### PR DESCRIPTION
**Pull request by TrentHouliston**
Adds tools for working with nbs files in c++.
Contains a decoder that can read through an nbs file and an encoder for writing them

### CODE REVIEW

**Comment by JosephusPaye** [comment]
While we're at it, it would be nice to get the fix for the broken NBS index generation. Currently index files created during DataLogging recording are invalid, and I think this was fixed on the 4tel end.

**Comment by TrentHouliston** [comment]
Will do in another PR once this one gets merged

**Review by Bidski — CHANGES_REQUESTED** [review]
DataLogger will need to be updated to use this Encoder? Same with DataPlayback?

**Review by Bidski — APPROVED** [review]
Fine

**Pull request merged**
