### PR TITLE
Remove 'enum' specifier from template declarations which caused warnings

### PR DESCRIPTION
**Pull request by KipHamiltons**
This PR gets rid of the `enum template` warnings by removing the `enum` specifier. :man_shrugging:

### CODE REVIEW

**Review by TrentHouliston — CHANGES_REQUESTED** [review]
I refuse!
Plz remove -Wpedantic instead!

**Comment by TrentHouliston** [comment]
Actually... I approve so long as this still enforces that you can only put a value from the enum in there

**Comment by CMurtagh-LGTM** [comment]
I agree with Trent here, we shouldn't religiously stick with ISO c++ when we have the option for neater looking code.

**Comment by KipHamiltons** [comment]
> Actually... I approve so long as this still enforces that you can only put a value from the enum in there

That's what it does ;) https://godbolt.org/z/d73rc3cdb

**Review by TrentHouliston — APPROVED** [review]

**Pull request merged**
