### PR TITLE
Patch intel-compute-runtime to resolve a memory leak

### PR DESCRIPTION
**Pull request by CMurtagh-LGTM**
Apply the patch from https://github.com/intel/compute-runtime/pull/550 into the version we use.

### CODE REVIEW

**Comment by KipHamiltons** [comment]
Have you considered `wget`ing the patch into a pipe into `patch`, such as we do in the IGC install script?

**Review by TrentHouliston — CHANGES_REQUESTED** [review]
The patch file is no longer needed

**Review by TrentHouliston — APPROVED** [review]
Wait nevermind I thought the second file was the patch file, turns out it's just that we have a custom build script for this

**Comment by CMurtagh-LGTM** [comment]
> Have you considered `wget`ing the patch into a pipe into `patch`, such as we do in the IGC install script?

I like this way better.

**Pull request merged**
