### PR TITLE
Removes OldWalkEngine

### PR DESCRIPTION
**Pull request by KipHamiltons**
I was going to remove other unused walk engines, but didn't know where to look for them.
Further purges of other stuff are coming soon :D

### CODE REVIEW

**Comment by ysims** [comment]
You can probably remove motion/walk/FootStep
It's not really useful and a better version is in the staticwalk2 branch.

**Comment by Bidski** [comment]
> You can probably remove motion/walk/FootStep
> It's not really useful and a better version is in the staticwalk2 branch.

QuinticWalk doesn't use `module/motion/walk/FootStep`, so just get rid of it.

**Review by Bidski — CHANGES_REQUESTED** [review]
Are there any other roles that need changing?

Are there any messages/utilities that are now redundant/unused after removing these modules?

**Comment by KipHamiltons** [comment]
I found a few unused Foot-related messages. I have added a commit which deletes them in this PR.
Otherwise, I couldn't find anything else which was previously used only by the OldWalkEngine or the FootStep which was removed.

**Review by Bidski — APPROVED** [review]
LGTM I guess

**Pull request merged**
