### PR TITLE
Added descriptions to protobuf messages

### PR DESCRIPTION
**Pull request by KipHamiltons**
Mission is to add brief descriptions to the proto messages, ready for the upcoming NUbots docu-lution.
Descriptions I didn't write:
~`SoccerObjectPriority.proto` has one message, which I have no idea how to describe.~
`Subsumption.proto` has one message and I am not sure about what it really does.
~`KickCommand.proto` has one `enum` `KickCommandType`, and I don't know what it means for a kick to be `NORMAL` vs `POWER` (also, we don't ever seem to do `POWER` kicks?)~

@TrentHouliston suggested I add descriptions to some of the nested objects. I have done this for `Behaviour.proto`, `FieldTarget.proto`, `FixedWalkCommand.proto`, `KickPlan.proto` so far. Was this along the lines you were thinking?

### CODE REVIEW

**Comment by ysims** [comment]
`POWER` is probs the penalty kicks. They're designed to kick the ball in one go from about... I think it's halfway between the goals and center... into the goal, with no consideration for the welfare of the robot.

**Comment by KipHamiltons** [comment]
> `POWER` is probs the penalty kicks. They're designed to kick the ball in one go from about... I think it's halfway between the goals and center... into the goal, with no consideration for the welfare of the robot.

I don't think it was ever implemented. I can't find anywhere in the code which checks what value it has. The only time it's ever mentioned I could find is in `KickPlanner.cpp` where in both cases a command is created with it set to `NORMAL`.

**Comment by ysims** [comment]
> > `POWER` is probs the penalty kicks. They're designed to kick the ball in one go from about... I think it's halfway between the goals and center... into the goal, with no consideration for the welfare of the robot.
> 
> I don't think it was ever implemented. I can't find anywhere in the code which checks what value it has. The only time it's ever mentioned I could find is in `KickPlanner.cpp` where in both cases a command is created with it set to `NORMAL`.

Yeah I don't remember it being used. At Sydney we just used ScriptRunner. It would be good to use in the future, but that would require writing some behaviour to go with it. Like 'when you have a clear shot of the goals, POWER KICK!'

**Comment by KipHamiltons** [comment]
> > > `POWER` is probs the penalty kicks. They're designed to kick the ball in one go from about... I think it's halfway between the goals and center... into the goal, with no consideration for the welfare of the robot.
> > 
> > 
> > I don't think it was ever implemented. I can't find anywhere in the code which checks what value it has. The only time it's ever mentioned I could find is in `KickPlanner.cpp` where in both cases a command is created with it set to `NORMAL`.
> 
> Yeah I don't remember it being used. At Sydney we just used ScriptRunner. It would be good to use in the future, but that would require writing some behaviour to go with it. Like 'when you have a clear shot of the goals, POWER KICK!'. Although it can hurt the robot.

I'll add a comment for it, now I know what the purpose is

**Comment by TrentHouliston** [comment]
Power was implemented as a way to swap between our nice gentler kicks and our full power kick. I'm not sure it ever was integrated super well. SoccerObjectPriority is designed to prioritise what the head behaviour should look at. So if it's looking for ball first then goal, or goal then ball etc

**Comment by KipHamiltons** [comment]
> SoccerObjectPriority is designed to prioritise what the head behaviour should look at. So if it's looking for ball first then goal, or goal then ball etc

Added.

**Pull request closed without merging**
