### PR TITLE
Remove eSpeak module

### PR DESCRIPTION
**Pull request by KipHamiltons**
This module is unused and I don't think we have plans to use it in the future. This PR removes it, as well as removing the dependencies it required.
Relates to #398

### CODE REVIEW

**Review by ysims — COMMENTED** [review]
I'm not opposed to removing it since we really don't use it right now. But we eventually do want to do something like this with the @home robot.

**Review by TrentHouliston — COMMENTED** [review]
You should keep this, and make it work.
It was super useful to be able to have the robot say things when it's running on the field and you can't just terminal into it.

**Comment by Bidski** [comment]
> You should keep this, and make it work.
> It was super useful to be able to have the robot say things when it's running on the field and you can't just terminal into it.

While I agree we should keep this, it is currently dependant on hardware that we no longer have

**Comment by KipHamiltons** [comment]
> > You should keep this, and make it work.
> > It was super useful to be able to have the robot say things when it's running on the field and you can't just terminal into it.
> 
> While I agree we should keep this, it is currently dependant on hardware that we no longer have

So you're advocating keeping this @Bidski?

**Comment by TrentHouliston** [comment]
I mean the hardware you no longer have is literally a speaker... It's not like it's some esoteric weird hardware that we will never have again.

Plug something into the NUC's headphone port and boom you have hardware again

We actually had plans to replace that little radiation symbol on the chest with a little speaker already right @tayloryoung6396

**Comment by Bidski** [comment]
> So you're advocating keeping this @Bidski?

I am. Just because a module is not being used, doesn't mean it is useless (or not worth keeping). Just putting it out there that there is a hardware dependency for this module

**Comment by KipHamiltons** [comment]
Roger that. If we think this is worth keeping, that's all good by me. Closing

**Pull request closed without merging**
