### PR TITLE
Autocomplete

### PR DESCRIPTION
**Pull request by CMurtagh-LGTM**
Implements  #657

on bash run
```
eval "$(register-python-argcomplete b)"
```

on zsh run
```
autoload -U bashcompinit
bashcompinit
eval "$(register-python-argcomplete b)"
```

https://github.com/NUbots/NUbook/pull/161

### CODE REVIEW

**Comment by KipHamiltons** [comment]
Where are you going to document this feature? I don't want to approve this until you have made a NUbook PR, if that's what's appropriate

**Comment by CMurtagh-LGTM** [comment]
We're going to need to add the new python package to the build machines

**Comment by KipHamiltons** [comment]
Now that we have github actions, is there anything which needs to be done for this PR @CMurtagh-LGTM?

**Comment by CMurtagh-LGTM** [comment]
This needs argcomplete to be installed on the runner.

**Comment by KipHamiltons** [comment]
Well, there are three solutions which come to my mind: 
1. `try: import module; do_module_thing(); except ImportError: pass` (My preferred solution I think, because then people aren't forced to get autocomplete package if they don't want it as well
2. `pip install <module>` as part of the pipeline
3. `pip install -r requirements.txt` as part of the pipeline.

**Comment by Y0sh1dk** [comment]
This appears to work well for me on zsh. I already had `argcomplete` installed globally though and cannot see where we install `nuclear/requirements.txt`. Should we update the docs to install the nuclear requirements as well @CMurtagh-LGTM? or possibly move `argcomplete` into the root level requirements

**Review by Y0sh1dk — APPROVED** [review]
LGTM, works well on zsh

**Pull request merged**
