### PR TITLE
Removes repeated measurement from goals measure

### PR DESCRIPTION
**Pull request by KipHamiltons**

### CODE REVIEW

**Review by CMurtagh-LGTM — APPROVED** [review]
lgtm

**Review by TrentHouliston — CHANGES_REQUESTED** [review]
Why are we removing repeated measurements from goalposts? just because we're not using them right now doesn't mean they're important!

You are able to measure the distance to the goal posts by both projecting to the centre like you are now, but also by measuring the goal post width. Therefore two measurements.

Someone just needs to reimplement the goal post width using the SVD stuff at some point

**Review by Bidski — CHANGES_REQUESTED** [review]
I agree with @TrentHouliston this PR serves no purpose. It removes code that causes no harm, but which we will have to add again later on

**Comment by KipHamiltons** [comment]
I was actioning a TODO on one of the localisation PRs, but if you guys think it's a bad idea, I am quite fine with closing.

**Pull request closed without merging**
