### PR TITLE
Sets Sensorfilter log level using new construct to NUClear::ERROR

### PR DESCRIPTION
**Pull request by KipHamiltons**
Also changes cholesky decomps to be warnings, so that they don't clog up the robocup logs. Given that we can now recover from cholesky decomp errors, this seems like the right log level anyway

### CODE REVIEW

**Comment by KipHamiltons** [comment]
Updated to use new log_level nice thing

**Review by CMurtagh-LGTM — APPROVED** [review]
Looks Good To Me

**Review by TrentHouliston — APPROVED** [review]
And by new, you mean only introduced about 8 years ago or so :P

**Review by Bidski — APPROVED** [review]
Seems reasonable

**Review by miikyla — COMMENTED** [review]
Looks good!

**Pull request merged**
