### PR TITLE
Change webots image format from BGR3 to RGBA

### PR DESCRIPTION
**Pull request by Tom0Brien**
This PR changes webots image format from BGR3 to RGBA.

Requires https://github.com/NUbots/NUWebots/pull/103

### CODE REVIEW

**Review by ysims — COMMENTED** [review]
The extract images tool would also need to be updated iirc.
This looks like it would break vision when using the official robocup world?

**Comment by Tom0Brien** [comment]
> The extract images tool would also need to be updated iirc. This looks like it would break vision when using the official robocup world?

Looks like extract image tool saves images as JPEG so should be fine. 

Vision shouldn't break, let me confirm.

**Comment by Tom0Brien** [comment]
> > The extract images tool would also need to be updated iirc. This looks like it would break vision when using the official robocup world?
> 
> Looks like extract image tool saves images as JPEG so should be fine.
> 
> Vision shouldn't break, let me confirm.

I see what you mean now with the `player` controller in `hlvs_webots`. We could make a fork and fix it or do the format conversion on the NUbots side only. Let's put this PR on hold for now until we can get `opencl` working in docker because its not important unless it helps with that

**Comment by ysims** [comment]
Can the branch be deleted too

**Pull request closed without merging**
