### PR TITLE
Fixes NatNet so that it compiles.

### PR DESCRIPTION
**Pull request by ysims**
NatNet didn't compile. This wasn't noticed because it's not in any roles. 
Looks like `MotionCapture.proto` was changed to snake_case and no one realised it affected NatNet.
Changed `frameNumber` to `frame_number` in `MotionCapture.proto` since it seemed to be the only thing not snake_case in there.

### CODE REVIEW

**Review by Bidski — CHANGES_REQUESTED** [review]
Had a quick look. Seems ok (maybe get a second opinion, this is hard to read on my phone). Also, you should make sure there is role that builds this module

**Review by CMurtagh-LGTM — APPROVED** [review]
LGTM

**Comment by KipHamiltons** [comment]
@Bidski

**Review by Bidski — APPROVED** [review]
Sure

**Pull request merged**
