### PR TITLE
Remove the name from the container

### PR DESCRIPTION
**Pull request by TrentHouliston**
Don't name the container, it means you can't run multiple ./b things at once (e.g. if you're in a ./b shell in one terminal you can't ./b build in another etc)

### CODE REVIEW

**Review by KipHamiltons — APPROVED** [review]
LGTM

**Comment by Y0sh1dk** [comment]
Would it be worth naming the container with the name of the tool that is ran (eg `nubots_shell` or `nubots_build`) so that we can tell container resource usage when running `docker stats`?

**Comment by KipHamiltons** [comment]
That sounds like a good idea to me!

**Comment by TrentHouliston** [comment]
Nah that's not a good idea. Then you'd only be able to run a single shell etc which is still limiting. This way it just gets a random name but if you do `docker ps` you'll still see the actual command that was run anyway

**Pull request merged**
